name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn clean test -Dheadless=true

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: project/reports/
